// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './nothing-you-could-do.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Nothing You Could Do',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Nothing You Could Do'; src: url(${fontUrl}); }`,
  unitsPerEm: 1024,
  ascender: 959,
  descender: -407,
  glyphData,
} as const;

export default bundle;
